In [ ]:
import pandas as pd
import numpy as np
pd.set_option('max_columns', 50)

In [ ]:
def make_tables():
    df_dict = {}
    for shot in [10, 50, 100, 200, 300]:
        df_dict[shot] = []
    for ds_name in ['customer', 'fashion_mnist', 'svhn']:
        print(ds_name)
        df0 = pd.read_csv(f'results/02-02-2021/results_{ds_name}_svd_o2m.csv')
        df = pd.read_csv(f'results/02-02-2021/results_{ds_name}_svd_o2m_v2.csv')
        df1 = pd.read_csv(f'results/02-02-2021/results_{ds_name}_bidir.csv')
        df2 = pd.read_csv(f'results/02-02-2021/results_{ds_name}_o2m.csv')
        df3 = pd.read_csv(f'results/02-02-2021/results_{ds_name}_logreg.csv')
        df4 = pd.read_csv(f'results/02-02-2021/results_{ds_name}_tree.csv')
        df5 = pd.read_csv(f'results/02-02-2021/results_{ds_name}_mlp.csv')
        df6 = pd.read_csv(f'results/02-02-2021/results_{ds_name}_o2mlog.csv')
        df1['model'] = 'Bidirectional distillation'
        df['model'] = 'SVD full O2M distillation'
        df0['model'] = 'SVD simple O2M distillation'
        df2['model'] = 'O2M distillation'
        df3['model'] = 'Logistic Regression'
        df4['model'] = 'Decision Tree'
        df5['model'] = 'MLP'
        df6['model'] = 'Logdistill O2M'
        df_concat = pd.DataFrame(columns=['model', 'dataset', 'train_shot', 'accuracy'])
        for single_df in [df0, df, df1, df2, df3, df4, df5, df6]:
            df_concat = pd.concat([df_concat, (single_df[single_df['train_shot'].isin([10, 50, 100, 200, 300])]
             .groupby(by=['model', 'dataset', 'train_shot'])
             .agg({'accuracy': 'max'})
             .reset_index())])
        for shot in [10, 50, 100, 200, 300]:
            df_dict[shot].append(df_concat[df_concat['train_shot'] == shot])
    for shot in [10, 50, 100, 200, 300]:
        df_dict[shot] = pd.concat(df_dict[shot]).drop(columns=['train_shot']).sort_values(by=['dataset', 'accuracy'])
    return df_dict

In [ ]:
df_dict = make_tables()

In [57]:
df_logMN = pd.read_csv('results/02-02-2021/results_mnist_o2mlog.csv')

In [46]:
df_logMN[df_logMN['train_shot'] == 10].sort_values(by=['accuracy'])

,dataset,epochs,way,train_shot,test_shot,x_dim,z_dim,dld,optimizer,lr,initialization,channels,loss,trials,silent,split,in_alphabet,add_rotations,gpu,test_batch,full_test,save_data,table_dataset,accuracy,duration_sec,lr_target
7,mnist,3,10,1,1,28,784,True,adam,0.00005,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.145,14.889441,0.00010
8,mnist,3,10,1,1,28,784,True,adam,0.00005,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.149,14.721480,0.00005
6,mnist,3,10,1,1,28,784,True,adam,0.00005,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.158,14.654553,0.00100
17,mnist,3,10,1,1,28,2000,True,adam,0.00005,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.194,25.468672,0.00005
16,mnist,3,10,1,1,28,2000,True,adam,0.00005,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.196,23.641985,0.00010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,mnist,3,10,300,1,28,2000,True,adam,0.00005,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.958,2011.911125,0.00005
212,mnist,10,10,300,1,28,2000,True,adam,0.00010,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.961,6778.355582,0.00005
215,mnist,10,10,300,1,28,2000,True,adam,0.00005,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.965,6791.727120,0.00005
103,mnist,3,10,300,1,28,2000,True,adam,0.00010,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.966,2019.588171,0.00010
104,mnist,3,10,300,1,28,2000,True,adam,0.00010,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.969,2062.025019,0.00005

In [65]:
for shot in [10, 50, 100, 200, 300]:
    (df_dict[shot]
     .pivot(index='model', columns='dataset', values='accuracy')
     .reset_index()
     .to_csv(f'results/02-02-2021/Results_{shot}_train_shot_aggregated_max.csv', index=False))

In [70]:
df_dict[10].pivot(index='model', columns='dataset', values='accuracy').reset_index()

dataset                        model  customer  fashion_mnist   svhn
0         Bidirectional distillation    0.6800          0.708  0.250
1                      Decision Tree    0.6850          0.553  0.139
2                     Logdistill O2M    0.6350          0.703  0.169
3                Logistic Regression    0.5550          0.618  0.112
4                                MLP    0.6300          0.536  0.109
5                   O2M distillation    0.6825          0.700  0.258
6          SVD full O2M distillation    0.6300          0.278  0.103
7        SVD simple O2M distillation    0.6750          0.709  0.311

In [71]:
df_dict[50].pivot(index='model', columns='dataset', values='accuracy').reset_index()

dataset                        model  customer  fashion_mnist   svhn
0         Bidirectional distillation     0.680          0.802  0.417
1                      Decision Tree     0.745          0.654  0.167
2                     Logdistill O2M     0.645          0.763    NaN
3                Logistic Regression     0.670          0.708  0.127
4                                MLP     0.740          0.706  0.124
5                   O2M distillation     0.655          0.779  0.279
6          SVD full O2M distillation     0.510          0.592  0.254
7        SVD simple O2M distillation     0.655          0.785  0.518

In [72]:
df_dict[100].pivot(index='model', columns='dataset', values='accuracy').reset_index()

dataset                        model  customer  fashion_mnist   svhn
0         Bidirectional distillation     0.680          0.830  0.412
1                      Decision Tree     0.760          0.698  0.214
2                     Logdistill O2M     0.705          0.809    NaN
3                Logistic Regression     0.665          0.768  0.130
4                                MLP     0.765          0.754  0.114
5                   O2M distillation     0.730          0.804  0.464
6          SVD full O2M distillation       NaN          0.741  0.412
7        SVD simple O2M distillation     0.690          0.800  0.527

In [73]:
df_dict[200].pivot(index='model', columns='dataset', values='accuracy').reset_index()

dataset                        model  customer  fashion_mnist   svhn
0         Bidirectional distillation     0.690          0.834    NaN
1                      Decision Tree     0.755          0.724  0.239
2                     Logdistill O2M       NaN          0.828    NaN
3                Logistic Regression     0.745          0.781  0.119
4                                MLP     0.805          0.776  0.111
5                   O2M distillation     0.735          0.837  0.491
6          SVD full O2M distillation       NaN          0.806  0.584
7        SVD simple O2M distillation     0.735          0.771  0.482

In [74]:
df_dict[300].pivot(index='model', columns='dataset', values='accuracy').reset_index()

dataset                        model  customer  fashion_mnist   svhn
0         Bidirectional distillation     0.760          0.848  0.362
1                      Decision Tree     0.750          0.734  0.298
2                     Logdistill O2M       NaN          0.823    NaN
3                Logistic Regression     0.695          0.790  0.130
4                                MLP     0.740          0.819  0.129
5                   O2M distillation     0.730          0.855  0.482
6          SVD full O2M distillation       NaN          0.847  0.637
7        SVD simple O2M distillation     0.720          0.768  0.407