In [12]:
from distutils.sysconfig import get_python_lib
print(get_python_lib())

/nfs/home/iglukhov/anaconda3/lib/python3.8/site-packages

In [13]:
import pandas as pd
import numpy as np
pd.set_option('max_columns', 50)

In [14]:
df_mnist = pd.read_csv('results/02-02-2021/results_mnist_svd_o2m.csv')

In [16]:
df_mnist.sort_values(by=['accuracy'])

,dataset,epochs,way,train_shot,test_shot,x_dim,z_dim,dld,optimizer,lr,initialization,channels,loss,trials,silent,split,in_alphabet,add_rotations,gpu,test_batch,full_test,save_data,table_dataset,accuracy,duration_sec
0,mnist,3,10,1,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.438,14.121992
14,mnist,10,10,1,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.438,8.507793
1,mnist,3,10,1,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.472,18.330229
15,mnist,10,10,1,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.472,17.825347
3,mnist,3,10,5,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.708,26.754900
17,mnist,10,10,5,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.708,25.776696
2,mnist,3,10,5,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.708,15.510432
16,mnist,10,10,5,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.708,12.776801
26,mnist,10,10,300,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.772,88.185493
12,mnist,3,10,300,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.772,89.949398
13,mnist,3,10,300,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.797,103.150980
27,mnist,10,10,300,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.797,103.758358
5,mnist,3,10,10,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.805,27.457892
19,mnist,10,10,10,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.805,26.190977
4,mnist,3,10,10,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.806,16.463820
18,mnist,10,10,10,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.806,16.753675
25,mnist,10,10,200,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.903,75.849227
11,mnist,3,10,200,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.903,73.558412
22,mnist,10,10,100,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.906,37.119922
8,mnist,3,10,100,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.906,39.147717
10,mnist,3,10,200,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.911,61.985768
24,mnist,10,10,200,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.911,60.932111
7,mnist,3,10,50,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.916,34.365341
21,mnist,10,10,50,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.916,33.369798
6,mnist,3,10,50,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.926,26.660834
20,mnist,10,10,50,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.926,24.757618
9,mnist,3,10,100,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.944,46.709163
23,mnist,10,10,100,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.944,47.140399

In [17]:
df_fmnist = pd.read_csv('results/02-02-2021/results_fashion_mnist_svd_o2m.csv')

In [18]:
df_fmnist.sort_values(by=['accuracy'])

,dataset,epochs,way,train_shot,test_shot,x_dim,z_dim,dld,optimizer,lr,initialization,channels,loss,trials,silent,split,in_alphabet,add_rotations,gpu,test_batch,full_test,save_data,table_dataset,accuracy,duration_sec
1,fashion_mnist,3,10,1,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.463,33.781158
15,fashion_mnist,10,10,1,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.463,27.504956
0,fashion_mnist,3,10,1,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.466,32.923303
14,fashion_mnist,10,10,1,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.466,13.423791
17,fashion_mnist,10,10,5,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.630,31.417650
3,fashion_mnist,3,10,5,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.630,31.728097
16,fashion_mnist,10,10,5,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.641,16.959957
2,fashion_mnist,3,10,5,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.641,17.819928
18,fashion_mnist,10,10,10,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.686,18.590729
4,fashion_mnist,3,10,10,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.686,19.752732
5,fashion_mnist,3,10,10,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.709,36.589026
19,fashion_mnist,10,10,10,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.709,35.379321
12,fashion_mnist,3,10,300,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.721,153.051543
26,fashion_mnist,10,10,300,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.721,151.050152
24,fashion_mnist,10,10,200,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.762,100.780651
10,fashion_mnist,3,10,200,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.762,104.419894
7,fashion_mnist,3,10,50,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.764,51.545894
21,fashion_mnist,10,10,50,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.764,50.018532
13,fashion_mnist,3,10,300,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.768,172.848907
27,fashion_mnist,10,10,300,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.768,175.916211
25,fashion_mnist,10,10,200,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.771,111.237138
11,fashion_mnist,3,10,200,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.771,109.817616
8,fashion_mnist,3,10,100,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.780,59.497247
22,fashion_mnist,10,10,100,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.780,61.324306
20,fashion_mnist,10,10,50,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.785,38.814799
6,fashion_mnist,3,10,50,1,28,784,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.785,38.188093
9,fashion_mnist,3,10,100,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.800,75.526253
23,fashion_mnist,10,10,100,1,28,2000,True,adam,0.001,xavier_normal,1,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.800,76.744297

In [19]:
df_svhn = pd.read_csv('results/02-02-2021/results_svhn_svd_o2m.csv')

In [20]:
df_svhn.sort_values(by=['accuracy'])

,dataset,epochs,way,train_shot,test_shot,x_dim,z_dim,dld,optimizer,lr,initialization,channels,loss,trials,silent,split,in_alphabet,add_rotations,gpu,test_batch,full_test,save_data,table_dataset,accuracy,duration_sec
0,svhn,3,10,1,1,32,1024,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.120,46.473406
14,svhn,10,10,1,1,32,1024,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.120,37.361210
1,svhn,3,10,1,1,32,2000,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.129,74.965604
15,svhn,10,10,1,1,32,2000,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.129,66.284745
3,svhn,3,10,5,1,32,2000,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.203,81.420547
17,svhn,10,10,5,1,32,2000,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.203,78.752709
2,svhn,3,10,5,1,32,1024,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.209,46.884992
16,svhn,10,10,5,1,32,1024,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.209,42.075555
4,svhn,3,10,10,1,32,1024,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.295,49.358678
18,svhn,10,10,10,1,32,1024,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.295,48.215369
5,svhn,3,10,10,1,32,2000,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.311,80.920114
19,svhn,10,10,10,1,32,2000,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.311,80.968514
12,svhn,3,10,300,1,32,1024,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.405,153.226066
26,svhn,10,10,300,1,32,1024,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.405,156.269382
13,svhn,3,10,300,1,32,2000,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.407,224.253822
27,svhn,10,10,300,1,32,2000,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.407,224.368314
10,svhn,3,10,200,1,32,1024,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.480,112.020609
24,svhn,10,10,200,1,32,1024,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.480,115.830354
25,svhn,10,10,200,1,32,2000,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.482,177.143922
11,svhn,3,10,200,1,32,2000,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.482,170.750249
6,svhn,3,10,50,1,32,1024,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.505,58.381023
20,svhn,10,10,50,1,32,1024,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.505,57.636542
7,svhn,3,10,50,1,32,2000,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.518,97.998105
21,svhn,10,10,50,1,32,2000,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.518,96.341223
8,svhn,3,10,100,1,32,1024,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.521,76.820400
22,svhn,10,10,100,1,32,1024,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.521,76.648087
9,svhn,3,10,100,1,32,2000,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.527,118.401651
23,svhn,10,10,100,1,32,2000,True,adam,0.001,xavier_normal,3,MSELoss(),100,True,test,False,True,1,2000,False,False,False,0.527,123.990704

In [21]:
df_customer = pd.read_csv('results/02-02-2021/results_customer_svd_o2m.csv')

In [22]:
df_customer.sort_values(by=['accuracy'])

,dataset,epochs,way,train_shot,test_shot,dld,x_dim,z_dim,optimizer,lr,initialization,loss,trials,silent,split,gpu,test_batch,full_test,save_data,table_dataset,accuracy,duration_sec
0,customer,3,2,1,1,True,41,2000,adam,0.001,xavier_normal,MSELoss(),100,False,train,1,1407,False,False,True,0.595,6.755239
7,customer,10,2,1,1,True,41,2000,adam,0.001,xavier_normal,MSELoss(),100,False,train,1,1407,False,False,True,0.620,3.608962
2,customer,3,2,50,1,True,41,2000,adam,0.001,xavier_normal,MSELoss(),100,False,train,1,1407,False,False,True,0.630,28.785719
8,customer,10,2,5,1,True,41,2000,adam,0.001,xavier_normal,MSELoss(),100,False,train,1,1407,False,False,True,0.650,10.187233
1,customer,3,2,5,1,True,41,2000,adam,0.001,xavier_normal,MSELoss(),100,False,train,1,1407,False,False,True,0.655,4.389646
9,customer,10,2,50,1,True,41,2000,adam,0.001,xavier_normal,MSELoss(),100,False,train,1,1407,False,False,True,0.655,85.574170
11,customer,10,2,100,1,True,41,2000,adam,0.001,xavier_normal,MSELoss(),100,False,train,1,1407,False,False,True,0.655,168.846148
3,customer,3,2,10,1,True,41,2000,adam,0.001,xavier_normal,MSELoss(),100,False,train,1,1407,False,False,True,0.660,6.615898
10,customer,10,2,10,1,True,41,2000,adam,0.001,xavier_normal,MSELoss(),100,False,train,1,1407,False,False,True,0.675,17.771852
12,customer,10,2,200,1,True,41,2000,adam,0.001,xavier_normal,MSELoss(),100,False,train,1,1407,False,False,True,0.675,340.037090
4,customer,3,2,100,1,True,41,2000,adam,0.001,xavier_normal,MSELoss(),100,False,train,1,1407,False,False,True,0.690,53.632207
6,customer,3,2,300,1,True,41,2000,adam,0.001,xavier_normal,MSELoss(),100,False,train,1,1407,False,False,True,0.700,154.039550
13,customer,10,2,300,1,True,41,2000,adam,0.001,xavier_normal,MSELoss(),100,False,train,1,1407,False,False,True,0.720,508.137866
5,customer,3,2,200,1,True,41,2000,adam,0.001,xavier_normal,MSELoss(),100,False,train,1,1407,False,False,True,0.735,101.257011

In [33]:
def make_tables():
    df_dict = {}
    for shot in [10, 50, 100, 200, 300]:
        df_dict[shot] = []
    for ds_name in ['customer', 'mnist', 'fashion_mnist', 'svhn']:
        print(ds_name)
        df = pd.read_csv(f'results/02-02-2021/results_{ds_name}_svd_o2m.csv')
        df2 = pd.read_csv(f'results/02-02-2021/results_{ds_name}_o2m.csv')
#         df3 = pd.read_csv(f'results/02-02-2021/results_{ds_name}_logreg.csv')
#         df4 = pd.read_csv(f'results/02-02-2021/results_{ds_name}_tree.csv')
#         df5 = pd.read_csv(f'results/02-02-2021/results_{ds_name}_mlp.csv')
        df['model'] = 'SVD O2M distillation'
        df2['model'] = 'O2M distillation'
#         df3['model'] = 'Logistic Regression'
#         df4['model'] = 'Decision Tree'
#         df5['model'] = 'MLP'
        df_concat = pd.DataFrame(columns=['model', 'dataset', 'train_shot', 'accuracy'])
        for single_df in [df, df2]:
            df_concat = pd.concat([df_concat, (single_df[single_df['train_shot'].isin([10, 50, 100, 200, 300])]
             .groupby(by=['model', 'dataset', 'train_shot'])
             .agg({'accuracy': 'max'})
             .reset_index())])
        for shot in [10, 50, 100, 200, 300]:
            df_dict[shot].append(df_concat[df_concat['train_shot'] == shot])
    for shot in [10, 50, 100, 200, 300]:
        df_dict[shot] = pd.concat(df_dict[shot]).drop(columns=['train_shot'])
    return df_dict

In [34]:
df_dict = make_tables()

customer
mnist
fashion_mnist
svhn

In [35]:
df_dict[10]

                  model        dataset  accuracy
0  SVD O2M distillation       customer    0.6750
0      O2M distillation       customer    0.6825
0  SVD O2M distillation          mnist    0.8060
0  SVD O2M distillation  fashion_mnist    0.7090
0      O2M distillation  fashion_mnist    0.7000
0  SVD O2M distillation           svhn    0.3110
0      O2M distillation           svhn    0.2580

In [37]:
for shot in [10, 50, 100, 200, 300]:
    (df_dict[shot]
     .pivot(index='model', columns='dataset', values='accuracy')
     .reset_index()
     .to_csv(f'results/02-02-2021/Results_{shot}_train_shot_svd.csv', index=False))

In [38]:
df_dict[10].pivot(index='model', columns='dataset', values='accuracy').reset_index()

dataset                 model  customer  fashion_mnist  mnist   svhn
0            O2M distillation    0.6825          0.700    NaN  0.258
1        SVD O2M distillation    0.6750          0.709  0.806  0.311

In [39]:
df_dict[50].pivot(index='model', columns='dataset', values='accuracy').reset_index()

dataset                 model  customer  fashion_mnist  mnist   svhn
0            O2M distillation     0.655          0.779    NaN  0.279
1        SVD O2M distillation     0.655          0.785  0.926  0.518

In [40]:
df_dict[100].pivot(index='model', columns='dataset', values='accuracy').reset_index()

dataset                 model  customer  fashion_mnist  mnist   svhn
0            O2M distillation      0.73          0.804    NaN  0.464
1        SVD O2M distillation      0.69          0.800  0.944  0.527

In [41]:
df_dict[200].pivot(index='model', columns='dataset', values='accuracy').reset_index()

dataset                 model  customer  fashion_mnist  mnist   svhn
0            O2M distillation     0.735          0.837    NaN    NaN
1        SVD O2M distillation     0.735          0.771  0.911  0.482

In [42]:
df_dict[300].pivot(index='model', columns='dataset', values='accuracy').reset_index()

dataset                 model  customer  fashion_mnist  mnist   svhn
0            O2M distillation      0.73          0.855    NaN  0.482
1        SVD O2M distillation      0.72          0.768  0.797  0.407